### ISSUE TITLE
Error while starting

### ISSUE THREAD

**Issue by BarrenWardo** [mat-sz/metastable#2]
I am trying to run it on a cloud server. Getting this error

`TypeError: Cannot read properties of undefined (reading 'includes')
    at https://atwia2fk5se8i4.r8.modal.host/assets/index-BqOaYBf1.js:258:25374
    at Array.some (<anonymous>)
    at get hardware (https://atwia2fk5se8i4.r8.modal.host/assets/index-BqOaYBf1.js:258:25364)
    at bS (https://atwia2fk5se8i4.r8.modal.host/assets/index-BqOaYBf1.js:44:4865)
    at t.Pt (https://atwia2fk5se8i4.r8.modal.host/assets/index-BqOaYBf1.js:44:20967)
    at t.trackAndCompute (https://atwia2fk5se8i4.r8.modal.host/assets/index-BqOaYBf1.js:44:20843)
    at t.get (https://atwia2fk5se8i4.r8.modal.host/assets/index-BqOaYBf1.js:44:20349)
    at t.j (https://atwia2fk5se8i4.r8.modal.host/assets/index-BqOaYBf1.js:44:39407)
    at gP.get (https://atwia2fk5se8i4.r8.modal.host/assets/index-BqOaYBf1.js:44:12095)
    at https://atwia2fk5se8i4.r8.modal.host/assets/index-BqOaYBf1.js:267:53731 `
    
  Logs :

> [@metastable/common]: Process started
> [@metastable/types]: Process started
> [@metastable/common]: Process exited (exit code 0), completed in 2s 61ms
> [@metastable/types]: Process exited (exit code 0), completed in 2s 196ms
> [@metastable/model-info]: Process started
> [@metastable/model-info]: Process exited (exit code 0), completed in 1s 735ms
> [@metastable/metastable]: Process started
> [@metastable/metastable]: Process exited (exit code 0), completed in 3s 236ms
> [@metastable/client]: Process started
> [@metastable/server]: Process started
> [@metastable/server]: Process exited (exit code 0), completed in 3s 392ms
> [@metastable/client]: vite v5.4.6 building for production...
> [@metastable/client]: transforming...
> [@metastable/client]: ✓ 644 modules transformed.
> [@metastable/client]: rendering chunks...
> [@metastable/client]: computing gzip size...
> [@metastable/client]: dist/index.html                                 0.49 kB │ gzip:   0.31 kB
> [@metastable/client]: dist/assets/logo-BvB6ukQC.svg                   1.00 kB │ gzip:   0.37 kB
> [@metastable/client]: dist/assets/InterTight-CMB3tgIJ.woff2         234.66 kB
> [@metastable/client]: dist/assets/InterTight-Italic-btKm-Q6Q.woff2  246.26 kB
> [@metastable/client]: dist/assets/index-O7UN1Kz5.css                  3.50 kB │ gzip:   1.09 kB
> [@metastable/client]: dist/assets/index-1bACY7KM.css                 62.67 kB │ gzip:  11.34 kB
> [@metastable/client]: dist/assets/index-DalVjgeR.js                  43.24 kB │ gzip:  13.90 kB
> [@metastable/client]: dist/assets/index-BqOaYBf1.js                 650.97 kB │ gzip: 203.41 kB
> [@metastable/client]: ✓ built in 8.63s
> [@metastable/client]: 
> [@metastable/client]: (!) Some chunks are larger than 500 kB after minification. Consider:
> [@metastable/client]: - Using dynamic import() to code-split the application
> [@metastable/client]: - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
> [@metastable/client]: - Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
> [@metastable/client]: Process exited (exit code 0), completed in 16s 130ms
> Done in 23s 335ms
> Server running on 0.0.0.0:5001

**Comment by mat-sz** [comment]
@BarrenWardo Hi, I've added a fix for this in ccdd66f05e00ff3472e3c4bb97d32c2018f63578. This error also means that you don't have a detectable GPU in your system, though. Not sure which cloud server are you using, but I don't think it will be much better compared to running this locally.

**Comment by BarrenWardo** [comment]
Hey @mat-sz thanks for fixing it. 

> This error also means that you don't have a detectable GPU in your system, though. Not sure which cloud server are you using, but I don't think it will be much better compared to running this locally.

Since, I was getting error, I tried it multiple times with different gpus & also without gpu. So, I ended up sending log where I run it without gpu.
