### ISSUE TITLE
Undetectable GPU

### ISSUE THREAD

**Issue by BarrenWardo** [mat-sz/metastable#3]
I am running it on cloud GPU - Nvidia T4 but GPU is not getting detected. I tried putting it to GPU only & then restarting it but it didn't work as well.

GPU Error:
<img width="620" alt="image" src="https://github.com/user-attachments/assets/7053bd47-6f37-45d4-978f-5551b8a8eb7c">

Available GPU:
<img width="1324" alt="image" src="https://github.com/user-attachments/assets/47868b6d-bd72-4a22-afb7-d4afd6713793">

Logs:

> (base) root@modal:~/metastable# yarn install && yarn build && yarn start
> ➤ YN0065: Yarn will periodically gather anonymous telemetry: https://yarnpkg.com/advanced/telemetry
> ➤ YN0065: Run yarn config set --home enableTelemetry 0 to disable
> 
> ➤ YN0000: · Yarn 4.5.0
> ➤ YN0000: ┌ Resolution step
> ➤ YN0000: └ Completed in 0s 367ms
> ➤ YN0000: ┌ Post-resolution validation
> ➤ YN0060: │ eslint is listed by your project with version 9.10.0 (pc92b6), which doesn't satisfy what eslint-plugin-import and other dependencies request (^8.57.0).
> ➤ YN0002: │ @metastable/client@workspace:packages/client doesn't provide @trpc/server (p8c12c), requested by @trpc/client and other dependencies.
> ➤ YN0002: │ @metastable/client@workspace:packages/client doesn't provide eslint (p97541), requested by eslint-plugin-react-hooks and other dependencies.
> ➤ YN0002: │ @metastable/server@workspace:packages/server doesn't provide electron (p1649d), requested by @metastable/metastable.
> ➤ YN0002: │ @metastable/server@workspace:packages/server doesn't provide electron-updater (pe6667), requested by @metastable/metastable.
> ➤ YN0002: │ metastable@workspace:. doesn't provide typescript (p2a523), requested by @typescript-eslint/eslint-plugin and other dependencies.
> ➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
> ➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
> ➤ YN0000: └ Completed
> ➤ YN0000: ┌ Fetch step
> ➤ YN0013: │ 941 packages were added to the project (+ 772.1 MiB).
> ➤ YN0000: └ Completed in 23s 350ms
> ➤ YN0000: ┌ Link step
> ➤ YN0007: │ electron@npm:32.1.2 must be built because it never has been before or the last one failed
> ➤ YN0007: │ exifreader@npm:4.23.5 must be built because it never has been before or the last one failed
> ➤ YN0007: │ sharp@npm:0.33.5 must be built because it never has been before or the last one failed
> ➤ YN0007: │ esbuild@npm:0.23.1 must be built because it never has been before or the last one failed
> ➤ YN0007: │ esbuild@npm:0.21.5 must be built because it never has been before or the last one failed
> ➤ YN0000: └ Completed in 16s 649ms
> ➤ YN0000: · Done with warnings in 40s 891ms
> [@metastable/common]: Process started
> [@metastable/types]: Process started
> [@metastable/common]: Process exited (exit code 0), completed in 1s 888ms
> [@metastable/types]: Process exited (exit code 0), completed in 1s 996ms
> [@metastable/model-info]: Process started
> [@metastable/model-info]: Process exited (exit code 0), completed in 1s 609ms
> [@metastable/metastable]: Process started
> [@metastable/metastable]: Process exited (exit code 0), completed in 3s 51ms
> [@metastable/client]: Process started
> [@metastable/server]: Process started
> [@metastable/server]: Process exited (exit code 0), completed in 3s 19ms
> [@metastable/client]: vite v5.4.6 building for production...
> [@metastable/client]: transforming...
> [@metastable/client]: ✓ 646 modules transformed.
> [@metastable/client]: rendering chunks...
> [@metastable/client]: computing gzip size...
> [@metastable/client]: dist/index.html                                 0.49 kB │ gzip:   0.31 kB
> [@metastable/client]: dist/assets/logo-BvB6ukQC.svg                   1.00 kB │ gzip:   0.37 kB
> [@metastable/client]: dist/assets/Inconsolata-BlX5Rdmz.woff2        150.32 kB
> [@metastable/client]: dist/assets/InterTight-CMB3tgIJ.woff2         234.66 kB
> [@metastable/client]: dist/assets/InterTight-Italic-btKm-Q6Q.woff2  246.26 kB
> [@metastable/client]: dist/assets/index-O7UN1Kz5.css                  3.50 kB │ gzip:   1.09 kB
> [@metastable/client]: dist/assets/index-Cds11B30.css                 64.10 kB │ gzip:  11.58 kB
> [@metastable/client]: dist/assets/index-BCsY11_F.js                  43.24 kB │ gzip:  13.90 kB
> [@metastable/client]: dist/assets/index-BvET8-KN.js                 652.11 kB │ gzip: 203.85 kB
> [@metastable/client]: ✓ built in 8.79s
> [@metastable/client]: 
> [@metastable/client]: (!) Some chunks are larger than 500 kB after minification. Consider:
> [@metastable/client]: - Using dynamic import() to code-split the application
> [@metastable/client]: - Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
> [@metastable/client]: - Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
> [@metastable/client]: Process exited (exit code 0), completed in 15s 670ms
> Done in 22s 358ms
> Server running on 0.0.0.0:5001
> [Backend (stdout)] Starting ComfyUI server
> 
> [Backend (stdout)] Ready!
> [Backend (stdout)] 
> 
> Error in tRPC handler on path 'project.file.all': Error: Project not found
>     at ProjectRepository.get (file:///root/metastable/packages/metastable/lib/data/project.js:181:19)
>     ... 3 lines matching cause stack trace ...
>     at async callRecursive (file:///root/metastable/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:152:32) {
>   code: 'INTERNAL_SERVER_ERROR',
>   name: 'TRPCError',
>   [cause]: Error: Project not found
>       at ProjectRepository.get (file:///root/metastable/packages/metastable/lib/data/project.js:181:19)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async file:///root/metastable/packages/metastable/lib/trpc.js:315:33
>       at async resolveMiddleware (file:///root/metastable/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:102:30)
>       at async callRecursive (file:///root/metastable/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:152:32)
> }
> Error in tRPC handler on path 'project.file.onChange': Error: Project not found
>     at ProjectRepository.get (file:///root/metastable/packages/metastable/lib/data/project.js:181:19)
>     ... 3 lines matching cause stack trace ...
>     at async callRecursive (file:///root/metastable/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:152:32) {
>   code: 'INTERNAL_SERVER_ERROR',
>   name: 'TRPCError',
>   [cause]: Error: Project not found
>       at ProjectRepository.get (file:///root/metastable/packages/metastable/lib/data/project.js:181:19)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async file:///root/metastable/packages/metastable/lib/trpc.js:376:33
>       at async resolveMiddleware (file:///root/metastable/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:102:30)
>       at async callRecursive (file:///root/metastable/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:152:32)
> }
> Error in tRPC handler on path 'project.file.all': Error: Project not found
>     at ProjectRepository.get (file:///root/metastable/packages/metastable/lib/data/project.js:181:19)
>     ... 3 lines matching cause stack trace ...
>     at async callRecursive (file:///root/metastable/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:152:32) {
>   code: 'INTERNAL_SERVER_ERROR',
>   name: 'TRPCError',
>   [cause]: Error: Project not found
>       at ProjectRepository.get (file:///root/metastable/packages/metastable/lib/data/project.js:181:19)
>       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>       at async file:///root/metastable/packages/metastable/lib/trpc.js:315:33
>       at async resolveMiddleware (file:///root/metastable/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:102:30)
>       at async callRecursive (file:///root/metastable/node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:152:32)
> }

**Comment by mat-sz** [comment]
@BarrenWardo Could you try using the Docker version? It uses CUDA. Requires `nvidia-container-runtime` to be configured in your system.

I'll try to figure out how to exactly detect those GPUs but the code I have was made with consumer GPUs in mind.

**Comment by BarrenWardo** [comment]
> Requires `nvidia-container-runtime` to be configured in your system.

@mat-sz 

I installed it & tried but still it is showing the same issue.

<img width="575" alt="image" src="https://github.com/user-attachments/assets/db65edba-f595-4b64-90cd-69b205fd965f">

**Comment by mat-sz** [comment]
@BarrenWardo I meant using the Docker container (as mentioned in README), just the runtime by itself won't help.

**Comment by mat-sz** [comment]
@BarrenWardo Could you try 5b707484d4d946e706ddc4e645a7d22e847d8665 either way? Should improve the detection - you might need to reset your bundle though in Settings -> About Metastable.

**Comment by BarrenWardo** [comment]
@mat-sz I tried. Still same issue.

**Comment by mat-sz** [comment]
@BarrenWardo This maybe? 9259acfd3d8ac212825fafbb3622c88a35001a08

Make sure to run `yarn build` again. I'm testing on Runpod and it works on my end.

**Comment by BarrenWardo** [comment]
Hey @mat-sz ! It's working now.
